---
- name: Audit Log4j Versions in Containers
  hosts: all
  become: yes
  tasks:
    - name: Get Log4j version from each container
      ansible.builtin.command: "docker exec {{ item }} cat /logs/log4j_version.txt"
      register: log4j_results
      failed_when: false
      changed_when: false
      loop:
        - log4j_v1
        - log4j_v2
        - log4j_v3

    - name: Identify vulnerable Log4j versions
      ansible.builtin.debug:
        msg: "Container {{ item.item }} is using Log4j version {{ item.stdout }} - Vulnerable!"
      when: "'2.14' in item.stdout or '2.15.0' in item.stdout"
      loop: "{{ log4j_results.results }}"